{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 37,
   "id": "4f566743-925b-4e98-81c7-6804f3e3f03e",
   "metadata": {},
   "outputs": [],
   "source": [
    "import sqlite3\n",
    "import pandas as pd\n",
    "import logging\n",
    "from ingestion_db import ingest_db\n",
    "\n",
    "logging.basicConfig(\n",
    "    filename=\"logs/get_vendor_summary.log\",\n",
    "    level=logging.DEBUG,\n",
    "    format=\"%(asctime)s - %(levelname)s - %(message)s\",\n",
    "    filemode=\"a\"\n",
    ")\n",
    "\n",
    "def create_vendor_summary(conn):\n",
    "\n",
    "    query = \"\"\"\n",
    "    WITH FreightSummary AS (\n",
    "        SELECT \n",
    "            VendorNumber, \n",
    "            SUM(Freight) AS FreightCost\n",
    "        FROM vendor_invoice\n",
    "        GROUP BY VendorNumber\n",
    "    ),\n",
    "\n",
    "    PurchaseSummary AS (\n",
    "        SELECT\n",
    "            p.VendorNumber,\n",
    "            p.VendorName,\n",
    "            p.Brand,\n",
    "            p.Description,\n",
    "            p.PurchasePrice, \n",
    "            pp.Price AS ActualPrice, \n",
    "            pp.Volume,\n",
    "            SUM(p.Quantity) AS TotalPurchaseQuantity,\n",
    "            SUM(p.Dollars) AS TotalPurchaseDollars\n",
    "        FROM purchases p\n",
    "        JOIN purchase_prices pp\n",
    "            ON p.Brand = pp.Brand\n",
    "        WHERE p.PurchasePrice > 0\n",
    "        GROUP BY \n",
    "            p.VendorNumber, p.VendorName, p.Brand, p.Description, \n",
    "            p.PurchasePrice, pp.Price, pp.Volume\n",
    "    ),\n",
    "\n",
    "    SalesSummary AS (\n",
    "        SELECT\n",
    "            VendorNo,\n",
    "            Brand,\n",
    "            SUM(SalesQuantity) AS TotalSalesQuantity,\n",
    "            SUM(SalesDollars) AS TotalSalesDollars,\n",
    "            SUM(SalesPrice) AS TotalSalesPrice,\n",
    "            SUM(ExciseTax) AS TotalExciseTax\n",
    "        FROM sales\n",
    "        GROUP BY VendorNo, Brand\n",
    "    )\n",
    "\n",
    "    SELECT\n",
    "        ps.VendorNumber, \n",
    "        ps.VendorName, \n",
    "        ps.Brand,\n",
    "        ps.Description,\n",
    "        ps.PurchasePrice, \n",
    "        ps.ActualPrice, \n",
    "        ps.Volume, \n",
    "        ps.TotalPurchaseQuantity, \n",
    "        ps.TotalPurchaseDollars,\n",
    "        ss.TotalSalesQuantity, \n",
    "        ss.TotalSalesDollars, \n",
    "        ss.TotalSalesPrice, \n",
    "        ss.TotalExciseTax, \n",
    "        fs.FreightCost\n",
    "    FROM PurchaseSummary ps\n",
    "    LEFT JOIN SalesSummary ss\n",
    "        ON ps.VendorNumber = ss.VendorNo\n",
    "        AND ps.Brand = ss.Brand\n",
    "    LEFT JOIN FreightSummary fs\n",
    "        ON ps.VendorNumber = fs.VendorNumber\n",
    "    ORDER BY ps.TotalPurchaseDollars DESC\n",
    "    \"\"\"\n",
    "\n",
    "    return pd.read_sql_query(query, conn)\n",
    "\n",
    "\n",
    "def clean_data(df):\n",
    "\n",
    "    df['Volume'] = df['Volume'].astype(float)\n",
    "    df.fillna(0, inplace=True)\n",
    "\n",
    "    df['VendorName'] = df['VendorName'].str.strip()\n",
    "    df['Description'] = df['Description'].str.strip()\n",
    "\n",
    "    df['GrossProfit'] = df['TotalSalesDollars'] - df['TotalPurchaseDollars']\n",
    "    df['ProfitMargin'] = (df['GrossProfit'] / df['TotalSalesDollars']) * 100\n",
    "    df['StockTurnover'] = df['TotalSalesQuantity'] / df['TotalPurchaseQuantity']\n",
    "    df['SalesToPurchaseRatio'] = df['TotalSalesDollars'] / df['TotalPurchaseDollars']\n",
    "\n",
    "    return df\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    conn = sqlite3.connect(\"inventory.db\")\n",
    "\n",
    "    logging.info(\"Creating Vendor Summary Table.....\")\n",
    "    summary_df = create_vendor_summary(conn)\n",
    "    logging.info(summary_df.head())\n",
    "\n",
    "    logging.info(\"Cleaning Data.....\")\n",
    "    clean_df = clean_data(summary_df)\n",
    "    logging.info(clean_df.head())\n",
    "\n",
    "    logging.info(\"Ingesting data.....\")\n",
    "    ingest_db(clean_df, \"vendor_sales_summary\", conn)\n",
    "\n",
    "    logging.info(\"Completed \")\n",
    "    conn.close()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "f939d435-6ffc-4afc-beef-04798399a499",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e3aa1db4-ba61-4c26-86ee-ed4784ef6d57",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
